Generates correct mappings for Elasticsearch
non-searchable columns now get the `index: "not_analyzed"` mappings, so
their values aren't tokenized.

To reduce the impact of changes to searchable, navigable columns,
dropping individual relation is now possible.

diff --git a/search/mindbender-search b/search/mindbender-search
--- a/search/mindbender-search
+++ b/search/mindbender-search
@@ -6,14 +6,20 @@
 # 
 # To update the search index with new searchable data produced by DeepDive, run:
 # $ mindbender search update
-# You can specify which searchable entities to update:
-# $ mindbender search update [ENTITY]...
+# You can specify which searchable relations to update:
+# $ mindbender search update [RELATION]...
 # 
 # To check the search index status:
 # $ mindbender search status
 # 
-# For any reason, to destroy the search index, run:
-# $ mindbender search destroy
+# For any reason, to drop the search index, run:
+# $ mindbender search drop
+# Or specify the relation to drop:
+# $ mindbender search drop [RELATION]...
+# 
+# To see internal schema mappings:
+# $ mindbender search show-frontend-schema
+# $ mindbender search show-elasticsearch-mappings
 #
 ##
 # Author: Jaeho Shin <netj@cs.stanford.edu>
@@ -32,14 +38,18 @@ cd "$DEEPDIVE_APP"
 
 # parse command-line args
 case ${1:-} in
-    gui|update|status|destroy)
+    gui|update|status|drop)
         # make sure elasticsearch is running
         ${ELASTICSEARCH_RUNNING:-false} ||
             exec keep-elasticsearch-during -- "$0" "$@"
         Action=$1; shift
         ;;
+    show-frontend-schema|show-elasticsearch-mappings)
+        # no need for elasticsearch
+        Action=$1; shift
+        ;;
     *)
-        usage "$0" "No action given: gui, update, status, or destroy"
+        usage "$0" "Invalid action given: gui, update, status, or drop"
 esac
 
 # create a temporary space
@@ -49,13 +59,22 @@ trap "rm -rf $tmpdir" EXIT
 # simple wrapper for elasticsearch HTTP API
 esAPI() {
     local verb=$1 path=$2; shift 2
-    curl -fs -X$verb "$ELASTICSEARCH_BASEURL$path" "$@"
+    curl -sS -X$verb "$ELASTICSEARCH_BASEURL$path" "$@"
     echo  # because ES does not put an EOL
 }
 # shorthand for APIs on the index
 esAPIx() {
     local verb=$1 path=$2; shift 2
     esAPI "$verb" "/$ELASTICSEARCH_INDEX_NAME$path" "$@"
+}
+esAPIcheck() {
+    # translate error response into error messages and exit status
+    local errmsg=$(jq -e -r -s '
+        if length == 0 then "empty response"
+        else .[] | .error | select(.)
+        end | "Elasticsearch error: \(.)"
+    ')
+    [[ -z "$errmsg" ]] || error "$errmsg"
 }
 jqSchema() {
     if ! [[ -f "${DDLOG_SCHEMA_JSON:-}" ]]; then
@@ -66,13 +85,42 @@ jqSchema() {
     export DDLOG_SCHEMA_JSON
     jqDDlog <"$DDLOG_SCHEMA_JSON" "$@"
 }
+setDDlogRelationsSelected() {
+    # use relations specified over command-line to filter target relations
+    export DDLOG_RELATIONS_SELECTED
+    if [[ $# -eq 0 ]]; then
+        # default to all searchable entities discovered from DDlog
+        eval set -- $(jqSchema 'relations | .name | @sh')
+    else
+        # check errors in given names of relations
+        DDLOG_RELATIONS_SELECTED=$(
+            printf '%s\n' "$@" | jq -R -s -c 'rtrimstr("\n") | split("\n")')
+        badNames=$(jqSchema '
+            env.DDLOG_RELATIONS_SELECTED | fromjson[] |
+            select(
+                ([relationByName] | length == 0) or
+                (relationByName | isAnnotated([.name] | inside(["source", "extraction"])) | not)
+            )
+        ' -r)
+        [[ -z "$badNames" ]] ||
+            error "$badNames: must be a @source or @extraction relation"
+    fi
+    # filter down to only @source and @extraction relations
+    DDLOG_RELATIONS_SELECTED=$(jqSchema '[
+        relationsSelected |
+        annotated([.name] | inside(["source", "extraction"])) |
+        .name
+    ]' -c)
+    [[ "$DDLOG_RELATIONS_SELECTED" != "[]" ]] ||
+        error "No @source or @extraction relations found"
+}
 
 # perform action on search index
 case $Action in
     gui)
         # derive a schema for search frontend from DDlog
         DDLOG_SEARCH_SCHEMA="$tmpdir"/search-frontend-schema.json
-        jqSchema '[relations] | searchFrontendSchema' >"$DDLOG_SEARCH_SCHEMA"
+        jqSchema 'searchFrontendSchema' >"$DDLOG_SEARCH_SCHEMA"
         export DDLOG_SEARCH_SCHEMA
 
         # launch the GUI
@@ -80,40 +128,29 @@ case $Action in
         ;;
 
     update)
-        # use relations specified over command-line to filter target relations
-        export DDLOG_RELATIONS_SELECTED
-        if [[ $# -eq 0 ]]; then
-            # default to all searchable entities discovered from DDlog
-            eval set -- $(jqSchema 'relations | .name | @sh')
-        else
-            # check errors in given names of relations
-            DDLOG_RELATIONS_SELECTED=$(
-                printf '%s\n' "$@" | jq -R -s -c 'rtrimstr("\n") | split("\n")')
-            badNames=$(jqSchema '
-                env.DDLOG_RELATIONS_SELECTED | fromjson[] |
-                select(
-                    ([relationByName] | length == 0) or
-                    (relationByName | isAnnotated([.name] | inside(["source", "extraction"])) | not)
-                )
-            ' -r)
-            [[ -z "$badNames" ]] ||
-                error "$badNames: must be a @source or @extraction relation"
-        fi
-        # filter down to only @source and @extraction relations
-        DDLOG_RELATIONS_SELECTED=$(jqSchema '[
-            relationsSelected |
-            annotated([.name] | inside(["source", "extraction"])) |
-            .name
-        ]' -c)
-        [[ "$DDLOG_RELATIONS_SELECTED" != "[]" ]] ||
-            error "No @source or @extraction relations found"
-        # show which ones will be indexed first
-        jqSchema 'relationsSelected | "Will index relation \(.name)"' >&2
+        setDDlogRelationsSelected "$@"
 
         # set up parent-child mapping based on @references annotations
         # (See: https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html)
-        jqSchema '([ relationsSelected ] | elasticsearchMappingsForRelations)' |
-        esAPIx PUT "/" --data-binary @- >/dev/null || true
+        eval set -- $(jqSchema 'relationsSelected | .name | @sh' -r)
+        echo >&2 "Deriving mappings for relations $*"
+        mappings="$tmpdir"/mappings.json
+        jqSchema '[relationsSelected] | elasticsearchMappingsForRelations' >"$mappings"
+        if ! esAPIx GET "/" | esAPIcheck &>/dev/null; then
+            # create the index
+            echo >&2 "Creating index $ELASTICSEARCH_INDEX_NAME"
+            jq <"$mappings" '{mappings:.}' |
+            esAPIx PUT "/" --data-binary @- | esAPIcheck
+        else
+            # or update individual relations
+            for relation; do
+                # show which ones will be indexed first
+                echo >&2 "Updating mappings for relation $relation"
+                jq <"$tmpdir"/mappings.json "{ $relation: .$relation }" |
+                esAPIx PUT "/_mappings/$relation" --data-binary @- | esAPIcheck ||
+                    error "Retry after \`mindbender search drop $relation\`"
+            done
+        fi
 
         # bulk load to ES from DeepDive database
         update-relation() {
@@ -124,7 +161,7 @@ case $Action in
             # unload data from database in json lines
             deepdive sql eval "$sqlToUnload" format=json |
             # show progress
-            pv --line-mode --size="$(deepdive sql eval "SELECT COUNT(*) FROM ($sqlToUnload) r")" |
+            pv --line-mode --size="$(deepdive sql eval "SELECT COUNT(*) FROM $relation")" |
             # split records into multiple batches
             # TODO parallelize
             split --lines=$ELASTICSEARCH_BULK_BATCHSIZE --filter="$(escape-args-for-shell sh -euc '
@@ -132,7 +169,7 @@ case $Action in
                 # produce elasticsearch bulk load action for each JSON record
                 jq -c "$jqToFormat" |
                 # send them to elasticsearch
-                curl -fs -XPUT "$indexURL/_bulk" --data-binary @- |
+                curl -sS -XPUT "$indexURL/_bulk" --data-binary @- |
                 # discard all result but the error field
                 jq ".errors"
                 ' -- "$jqToFormat" "$ELASTICSEARCH_BASEURL/$ELASTICSEARCH_INDEX_NAME/$relation")" |
@@ -154,9 +191,27 @@ case $Action in
         esAPI GET '/_stats'
         ;;
 
-    destroy)
-        # delete the ES index
-        esAPIx DELETE "/"
+    drop)
+        if [[ $# -gt 0 ]]; then
+            # drop the given relations from the index
+            for relation; do
+                echo >&2 "Dropping relation $relation"
+                esAPIx DELETE "/$relation" | esAPIcheck
+            done
+        else
+            # drop the entire ES index
+            echo >&2 "Dropping entire index $ELASTICSEARCH_INDEX_NAME"
+            esAPIx DELETE "/" | esAPIcheck
+        fi
+        ;;
+
+    # show some internal schema mappings
+    show-frontend-schema)
+        jqSchema 'searchFrontendSchema'
+        ;;
+    show-elasticsearch-mappings)
+        setDDlogRelationsSelected "$@"
+        jqSchema '[ relationsSelected ] | elasticsearchMappingsForRelations'
         ;;
 
     *)
